# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-14 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160801_1208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users_login',
        ),
    ]
