# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-28 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audiofile', models.FileField(upload_to='recordings/%Y/%m/%d')),
            ],
        ),
    ]
