# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-08 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_recording'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recording',
        ),
    ]
