# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-09 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_recording'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='comments_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recording',
            name='likes_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recording',
            name='shares_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='answered_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='asked_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='audios_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='circle_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='followers_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='following_total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_details',
            name='intro',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='photo_link',
            field=models.URLField(default='static/sitewide/anonymous-male.png'),
        ),
        migrations.AddField(
            model_name='user_details',
            name='profile_link',
            field=models.URLField(default='/welcome_user'),
        ),
    ]
