# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-09 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_recording_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='photo_link',
            field=models.URLField(default='/static/sitewide/anonymous-male.png'),
        ),
    ]
