# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='follower_id',
            new_name='follower',
        ),
    ]
