# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-10 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20161024_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recording',
            name='title',
            field=models.CharField(default='Sample_audio', max_length=70),
        ),
    ]
